language: go

go:
  - 1.13.x

# Only clone the most recent commit.
git:
  depth: 1

script:
  - make test && bash <(curl -s https://codecov.io/bash)
  - make

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: bin/*
  skip_cleanup: true
  draft: true
  on:
    tags: true